apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.warehouses.name  }}
  labels:
    app: {{ .Values.warehouses.name  }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Values.warehouses.name  }}
      labels:
        app: {{ .Values.warehouses.name  }}
    spec:
      containers:
        - name: {{ .Values.warehouses.name  }}
          image: {{ .Values.warehouses.image  }}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{ .Values.warehouses.name  }}
