apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.warehouses.name  }}
  labels:
    app: {{ .Values.warehouses.name  }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ .Values.warehouses.name  }}
      labels:
        app: {{ .Values.warehouses.name  }}
    spec:
      containers:
        - name: {{ .Values.warehouses.name  }}
          image: {{ .Values.warehouses.image  }}
          imagePullPolicy: IfNotPresent
          env:
            - name: BrewUp__MongoDb__ConnectionString
              value: 'mongodb://root:t00rM3Pswd@brewup-mongodb.default.svc.cluster.local:27017/brewup-warehouses?authSource=admin'
            - name: BrewUp__MongoDb__DatabaseName
              value: 'brewup-warehouses'
            - name: BrewUp__RabbitMQ__Username
              value: {{.Values.rabbitmq.auth.username }}
            - name: BrewUp__RabbitMQ__Password
              value: {{.Values.rabbitmq.auth.password }}
            - name: BrewUp__RabbitMQ__Host
              value: {{.Values.serviceBus }}
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{ .Values.warehouses.name  }}
