apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-eventstore-{{.Values.warehouses.name}}
spec:
  type: ClusterIP
  ports:
    - name: external-tcp-port
      port: {{.Values.warehouses.eventStore.externalHttpPort}}
      targetPort: {{.Values.warehouses.eventStore.externalHttpPort}}
    - name: http-port
      port: {{.Values.warehouses.eventStore.httpPort}}
      targetPort: {{.Values.warehouses.eventStore.httpPort}}
  selector:
    app: eventstore-{{.Values.warehouses.name}}