apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.purchases.name}}
  labels:
    app: {{.Values.purchases.name}}
spec:
  replicas: 1
  template:
    metadata:
      name: {{.Values.purchases.name}}
      labels:
        app: {{.Values.purchases.name}}
    spec:
      containers:
        - name: {{.Values.purchases.name}}
          image: {{.Values.purchases.image}}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{.Values.purchases.name}}
