apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore-{{.Values.purchases.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstore-{{.Values.purchases.name}}
  template:
    metadata:
      labels:
        app: eventstore-{{.Values.purchases.name}}
    spec:
      containers:
        - name: eventstore-production
          image: eventstore/eventstore:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "1"
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: All
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: "true"
            - name: EVENTSTORE_EXT_TCP_PORT
              value: {{.Values.purchases.eventStore.externalHttpPort | quote }}
            - name: EVENTSTORE_HTTP_PORT
              value: {{.Values.purchases.eventStore.httpPort | quote }}
            - name: EVENTSTORE_INSECURE
              value: "true"
            - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
              value: "true"
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: "true"
            - name: EVENTSTORE_ALLOW_UNKNOWN_OPTIONS
              value: "true"
          ports:
            - containerPort: {{.Values.purchases.eventStore.externalHttpPort}}
            - containerPort: {{.Values.purchases.eventStore.httpPort}}
      restartPolicy: Always